version: 1

formatters:
  detail:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class : logging.StreamHandler
    formatter: detail
    level   : DEBUG
    stream  : ext://sys.stdout
  logfile:
    class: logging.FileHandler
    filename: lambda.log
    mode: 'w'
    level: DEBUG
    formatter: detail
loggers:
  lambda:
    level: DEBUG
    handlers: [logfile, console]
  yfinance:
    level: ERROR
    handlers: [logfile, console]
    